server:
  port: 8082
spring:
 datasource:
   driver: org.mariadb.jdbc.Driver
   url: jdbc:mariadb://localhost:3307/expensecodemodule
   username: root
   password: rootroot
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MariaDB103Dialect